apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-placement
  namespace: nginx
  labels:
    app: nginx-placement
spec:
  clusterConditions:
    - type: OK
  #clusters:
  #- name: gcp1-hive
  clusterSelector:
    matchLabels:
      environment: dev
  #clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
